server:
  port: 8092  # другой порт, чтобы не мешать Postgres-серверу

spring:
  application:
    name: api-app
  liquibase:
    change-log: classpath:db/changelog/db.changelog-anton.xml
    enabled: true

  datasource:
    url: jdbc:h2:mem:hotel-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS travel_business
    username: h2A
    password: 123
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
