server:
  port: 8092  # Порт приложения (не базы!)

spring:
  application:
    name: api-app
  main:
    allow-bean-definition-overriding: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-anton.xml
    enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/hotel-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_schema: PUBLIC

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    liquibase: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
