server:
  port: 8080

spring:
  application:
    name: api-app
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_app
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # либо validate/create при необходимости
    show-sql: true
    properties:
      hibernate:
        format_sql: true
